# Generated by Django 6.0 on 2025-12-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='journalrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата та час'),
        ),
        migrations.AlterField(
            model_name='journalrecord',
            name='department',
            field=models.CharField(choices=[('sales', 'Відділ продажів'), ('service', 'Відділ сервісу')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=20),
        ),
    ]
