# Generated by Django 6.0 on 2025-12-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_service_is_active_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalrecord',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='journal_records_many', to='apps.service'),
        ),
    ]
