# Generated by Django 6.0 on 2025-12-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_journalrecord_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalrecord',
            options={'ordering': ['-is_priority', '-date'], 'verbose_name': 'Запис журналу', 'verbose_name_plural': 'Записи журналу'},
        ),
        migrations.AddField(
            model_name='journalrecord',
            name='is_priority',
            field=models.BooleanField(default=False, verbose_name='Пріоритет'),
        ),
    ]
