# Generated by Django 6.0 on 2026-02-04 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_journalrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Початок')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Тривалість візиту у хвилинах', verbose_name='Тривалість, хв')),
                ('description', models.TextField(blank=True, verbose_name='Описание работ')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('done', 'Готово'), ('canceled', 'Отменено'), ('partially_done', 'Частично выполнено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='apps.client')),
                ('services', models.ManyToManyField(blank=True, related_name='appointments', to='apps.service', verbose_name='Послуги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_managed', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер/Сотрудник')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='apps.vehicle')),
            ],
            options={
                'verbose_name': 'Запис на сервіс',
                'verbose_name_plural': 'Записи на сервіс',
                'ordering': ['-start_time'],
            },
        ),
    ]
