# Generated by Django 6.0 on 2026-03-26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_appointment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="user2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments_managed_secondary",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Второй менеджер/Сотрудник",
            ),
        ),
    ]

