# Generated by Django 6.0 on 2026-04-01 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_add_appointment_user2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user2',
        ),
        migrations.AddField(
            model_name='appointment',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='appointments_managed', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
    ]
