# Generated by Django 6.0 on 2026-04-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_appointment_client'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('plate_number', 'brand', 'model', 'client'), name='unique_vehicle_per_client'),
        ),
    ]
